[project]
name = "example"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "certifi>=2017.4.17",
  "python-dotenv>=1.0.0",
  "requests>=2.31",
  "pandas>=2.2",
  "eth-abi>=5.2.0",
  "web3>=7.14.0",
  "eth-utils>=5.3.1",
]
